import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/navigation/header/Header";
import { Footer } from "@/components/navigation/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ShopCart online store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isStudio =
    typeof window !== "undefined" &&
    window.location.pathname.startsWith("/studio");
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="font-poppins antialiased">
          <div className="">
            {!isStudio && <Header />}
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </body>
      </html>{" "}
    </ClerkProvider>
  );
}
